spring.application.name=granja2
# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.ulztqnhulexlmviytxqd.supabase.co
spring.datasource.username=postgres
spring.datasource.password=BSgA+wk/79BTNg_
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10


